POST http://localhost:5000/api/users
Content-Type: application/json

{
 "username": "sanjay",
 "password": "123456"
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
 "username": "sanjay",
 "password": "123456"
}

###
POST http://localhost:5000/api/users/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTg2MTliMDM5N2E0NWJjN2I4MzY3YjciLCJpYXQiOjE3NzAzOTYyMjd9.dujCB6Bq7BG9NzxYqHr4WvezR2CDj0u-FEBBovRCrfs

###
POST http://localhost:5000/api/items
Content-Type: application/json

{
 "name": "iPhone 15",
 "price": 80000,
 "isAvailable": true,
 "imageUrl": "https://vsprod.vijaysales.com/media/catalog/product/2/2/220949-image1_2.jpg?optimize=medium&fit=bounds&height=500&width=500",
 "description": "Latest Apple smartphone with A16 chip",
 "category": "electronics"
}




###
GET http://localhost:5000/api/items


###
POST http://localhost:5000/api/carts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTg2MTliMDM5N2E0NWJjN2I4MzY3YjciLCJpYXQiOjE3NzAzOTcwMDV9.A_rA2L5BgOoX-5vNKNioFOhSwrtJIDL5F7cN3SAN534
Content-Type: application/json

{
 "itemId": "69861c3570ec25c7558bad67"
}
###
GET http://localhost:5000/api/carts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTg2MTliMDM5N2E0NWJjN2I4MzY3YjciLCJpYXQiOjE3NzAzOTcwMDV9.A_rA2L5BgOoX-5vNKNioFOhSwrtJIDL5F7cN3SAN534

###
POST http://localhost:5000/api/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTg2MTliMDM5N2E0NWJjN2I4MzY3YjciLCJpYXQiOjE3NzAzOTcwMDV9.A_rA2L5BgOoX-5vNKNioFOhSwrtJIDL5F7cN3SAN534

### Test for order creation with empty cart
Get http://localhost:5000/api/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTg2MTliMDM5N2E0NWJjN2I4MzY3YjciLCJpYXQiOjE3NzAzOTcwMDV9.A_rA2L5BgOoX-5vNKNioFOhSwrtJIDL5F7cN3SAN534

###
Get http://localhost:5000/api/users